In [30]:
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Acmegrade/automobile.csv'
import pandas as pd
df=pd.read_csv(path)
df.head(5)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


symboling  normalized-losses         make  ... horsepower-binned diesel gas
0          3                122  alfa-romero  ...            Medium      0   1
1          3                122  alfa-romero  ...            Medium      0   1
2          1                122  alfa-romero  ...            Medium      0   1
3          2                164         audi  ...            Medium      0   1
4          2                164         audi  ...            Medium      0   1

[5 rows x 29 columns]

In [31]:
df["normalized-losses"].corr(df["price"])

0.1339987342927433

In [32]:
df["bore"].corr(df["price"])

0.5431553832623075

In [33]:
df["compression-ratio"].corr(df["price"])

0.07110732668194136

In [34]:
df2=df[["normalized-losses","bore","compression-ratio","price"]]
df2.head()

normalized-losses  bore  compression-ratio  price
0                122  3.47                9.0  13495
1                122  3.47                9.0  16500
2                122  2.68                9.0  16500
3                164  3.19               10.0  13950
4                164  3.19                8.0  17450

In [35]:
import numpy as np
msk=np.random.rand(len(df2))<0.7
train_df=df2[msk]
test_df=df2[~msk]
X_train_df= train_df[["normalized-losses","bore","compression-ratio"]]
Y_train_df=train_df[["price"]]
X_test_df= test_df[["normalized-losses","bore","compression-ratio"]]
Y_test_df=test_df[["price"]]



In [36]:
X_train_df=np.asarray(X_train_df)
Y_train_df=np.asarray(Y_train_df)
X_test_df=np.asarray(X_test_df)
Y_test_df=np.asarray(Y_test_df)

In [37]:
from sklearn import linear_model
clf=linear_model.LinearRegression()
clf.fit(X_train_df,Y_train_df)
print(clf.coef_)
print("\n",clf.intercept_)

[[   40.71284934 15720.03706164   128.83478473]]

 [-45256.76208598]


In [38]:
Y_pred=clf.predict(X_test_df)

In [39]:
Y_pred[0:4]

array([[12597.74171022],
       [10952.21943031],
       [10952.21943031],
       [15590.0893265 ]])

In [40]:
X_test_df[0:4]

array([[164.  ,   3.19,   8.  ],
       [122.  ,   3.19,   8.5 ],
       [122.  ,   3.19,   8.5 ],
       [188.  ,   3.31,   9.  ]])

In [41]:
Y_test_df[0:4]

array([[17450],
       [15250],
       [18920],
       [20970]])

In [42]:
np.mean(np.abs(Y_pred-Y_test_df))

3672.2311130807357